### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by JoshuaWierenga** [Michael-Kelley/RoseOS#3]
Hi, I am attempting something [similar to this](https://github.com/JoshuaWierenga/EfiSharp) and noticed you have already solved some of the issues I am facing. And so I was wondering how you felt about me(or others) using some of your code?

**Comment by Michael-Kelley** [comment]
I just added the MIT license, so feel free to use the code however you want.

**Comment by JoshuaWierenga** [comment]
Thank You.
